In [14]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
dataset = pd.read_csv('2019.csv')
dataset.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [22]:
y = dataset['Score']
x = dataset['Social support']
def linear_regression(x, y):
    n = len(x)
    sum_x = sum(x)
    sum_y = sum(y)
    sum_xy = sum([x[i]*y[i] for i in range(n)])
    sum_x2 = sum([x[i]**2 for i in range(n)])
    a = (sum_y*sum_x2 - sum_x*sum_xy) / (n*sum_x2 - sum_x**2)
    b = (n*sum_xy - sum_x*sum_y) / (n*sum_x2 - sum_x**2)
    return a, b
linear_regression(x,y)

(1.912430244716382, 2.8909870440103176)

In [47]:
def predict(x, y):
    x = np.array(x).reshape(-1,1)
    y = np.array(y).reshape(-1,1)
    model = LinearRegression().fit(x,y)
    return model.predict(x)
predict(x,y)

array([[6.50042668],
       [6.45995286],
       [6.48597175],
       [6.6073932 ],
       [6.31251253],
       [6.32407647],
       [6.21132798],
       [6.41369707],
       [6.26336575],
       [6.17663613],
       [6.38767819],
       [6.07834258],
       [6.11881639],
       [6.18820008],
       [6.35876832],
       [6.40213312],
       [6.11592541],
       [6.26047476],
       [6.12459837],
       [6.21132798],
       [5.69962327],
       [6.30673055],
       [5.7372061 ],
       [6.16796317],
       [6.04654172],
       [5.87019151],
       [5.5810928 ],
       [5.83549966],
       [5.70829623],
       [6.20265502],
       [6.08123356],
       [6.0725606 ],
       [6.14772626],
       [6.14194429],
       [5.50303615],
       [6.21421897],
       [5.86730052],
       [6.26047476],
       [6.18241811],
       [6.06966961],
       [6.33274944],
       [6.29227562],
       [5.98872198],
       [6.31540351],
       [5.74298808],
       [5.47412628],
       [6.05232369],
       [5.47412628],
       [5.4481074 ],
       [5.70540525],
       [5.72564216],
       [5.98583099],
       [6.14772626],
       [5.43654345],
       [6.32985845],
       [6.1853091 ],
       [5.96559408],
       [6.01474086],
       [5.48569023],
       [6.27203871],
       [5.40763358],
       [5.98872198],
       [6.17663613],
       [5.53194602],
       [5.59554774],
       [6.0494327 ],
       [4.47384477],
       [6.11014343],
       [5.65047649],
       [5.91066533],
       [5.75166104],
       [5.67938636],
       [5.84706361],
       [5.08673402],
       [5.57241984],
       [5.6042207 ],
       [5.96270309],
       [5.41630654],
       [5.84417262],
       [5.29777607],
       [6.14772626],
       [5.25441127],
       [6.33853141],
       [5.65336748],
       [5.12431685],
       [6.06966961],
       [6.35876832],
       [5.26597522],
       [4.17318211],
       [5.22839238],
       [5.45099839],
       [5.39028766],
       [5.16479067],
       [5.80369881],
       [5.73142413],
       [4.54322845],
       [6.28649364],
       [4.421807  ],
       [4.24834778],
       [5.45678036],
       [5.45388937],
       [3.17579158],
       [4.22232889],
       [5.33246792],
       [4.8901469 ],
       [5.81815374],
       [4.36398726],
       [6.03786876],
       [5.15611771],
       [5.51749109],
       [5.19080955],
       [3.9303392 ],
       [5.70829623],
       [4.15005422],
       [4.96531256],
       [4.96242158],
       [4.34664134],
       [4.3090585 ],
       [3.83782762],
       [4.62706708],
       [4.75427051],
       [5.28621213],
       [4.76294347],
       [4.80341729],
       [4.59526622],
       [4.74559755],
       [5.16479067],
       [5.10697093],
       [4.34375035],
       [5.56952886],
       [5.32668594],
       [4.12692632],
       [5.93090224],
       [4.89881986],
       [5.23417436],
       [5.00289539],
       [4.91616578],
       [4.97109454],
       [3.56607483],
       [4.12403533],
       [4.5779203 ],
       [4.10090744],
       [4.56057438],
       [5.2919941 ],
       [3.20470145],
       [5.13298981],
       [3.90142933],
       [5.22261041],
       [3.00522335],
       [3.53138299],
       [5.27464818],
       [3.96792203],
       [4.47095378],
       [3.40707055],
       [1.91243024],
       [3.5747478 ]])

In [48]:
def score(x, y):
    mse = np.mean((y - x)**2)
    r_squared = 1 - (mse / np.var(y))
    return r_squared
score(x,y)

-13.971528656350376